Fix version download
honestica/docker-looker pull request #31
Opened 2023-01-27 09:04 UTC by marcmillien

## Context
Corrige l'erreur:
```
{"error":"Invalid Request"}curl: (6) Could not resolve host: null
The command '/bin/sh -c curl -Ss -X POST -H 'Content-Type: application/json' -d '{"lic": "'"$LICENSE"'", "email": "'"$EMAIL"'", "latest": "specific", "specific": "looker-'"$LOOKER_VERSION"'.jar"}' https://apidownload.looker.com/download > api_response.json   && cat api_response.json && curl -Ss "$(cat api_response.json | jq -r '.url')" -o $LOOKER_DIR/looker.jar   && curl -Ss "$(cat api_response.json | jq -r '.depUrl')" -o $LOOKER_DIR/looker-dependencies.jar' returned a non-zero code: 6
make: *** [Makefile:18: build] Error 6
```

2023-01-27 09:49 UTC, benoittgt commented
Bien vu!

2023-01-27 09:49 UTC, benoittgt approved these changes

2023-01-27 12:54 UTC, marcmillien commented
On en a discuté avec Dali, on va essayer de partir sur une solution plus pérenne en fournissant la version au Dockerfile et en allant chercher la version souhaitée dans circle.

2023-01-31 17:33 UTC, dadicool commented on .circleci/config.yml
> +      - setup_remote_docker:
ma remarque sur slack était de conserver l'étape `docker-build-and-push` ici et de lui passer les params qui vont bien apres avoir récupéré l'output de `full_version`

2023-01-31 18:04 UTC, dadicool commented on .circleci/config.yml
> +          dockerBuildOptions: --build-arg EMAIL=$EMAIL --build-arg LICENSE=$LICENSE --build-arg LOOKER_VERSION=LOOKER_VERSION
`LOOKER_VERSION=$LOOKER_VERSION`

2023-02-01 12:53 UTC, matthieudiehr approved these changes

2023-02-01 12:54 UTC, dadicool requested changes

2023-02-01 16:35 UTC, marcmillien commented on .circleci/config.yml
> +            echo "export LOOKER_VERSION="$(make version email=$EMAIL license=$LICENSE) >> "$BASH_ENV"
fixed :)

2023-02-01 19:37 UTC, dadicool approved these changes
Merci pour tous les changements !

2023-02-01 19:37 UTC, merged